name: _file
description: File Handler
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.5
  file_icon: ^1.0.0
  open_filex: ^4.3.2
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
